<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="Alarm_Display_ST" Id="{08e2e584-5ebd-4017-8838-0d3fbd977d4d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Alarm_Display_ST
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Alarm_Display_ST">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>