<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="Main" Id="{7de81d17-9477-439d-b1f6-5157a4a2df6c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Main
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Main">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>