<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="AutoStates_POU" Id="{b3a9f5a3-18ec-404a-a269-7e864e0ccca1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM AutoStates_POU
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="AutoStates_POU">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>